server:
  port: 9090 
  servlet:
    context-path: /fleetwood

security: 
  oauth2: 
    client: 
      client-id: Fleetwood
      client-secret: y471l12D2y55U5558rd2

# authorization server
accessTokenUri: http://localhost:8080/authorization/oauth/token
userAuthorizationUri: http://localhost:8080/authorization/oauth/authorize

# resource server
producerBaseURL: http://localhost:8081/sharewood/api/
sharewoodPhotoBaseURL: http://localhost:8081/sharewood/api/photos

#sharewoodCustomerBaseURL: http://localhost:8081/sharewood/api/customers

sharewoodTokenBaseURL: http://localhost:8080/authorization/api/tokens
    

# client
tempDir: /home/dominique/Pictures/client/tmp/

# Logging pattern for the console
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
 